version: '3.4'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
        - mongo-data:/data/db
    ports:
        - "27018:27017"
    networks:
        - common
    restart: always    

  redis:
    container_name: redis
    image: redis:latest
    volumes:
        - redis-data:/data
    ports:
        - "6378:6379"
    networks:
        - common
    restart: always

  booking-api:
    image: booking-api
    build:
      context: .
      target: api
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URL=mongodb://localhost:27018/admin
      - REDIS_URL=redis://localhost:6378
    networks:
        - common
    ports:
      - 3000:3000

  booking-worker:
    image: booking-worker
    build:
      context: .
      target: worker
      dockerfile: ./Dockerfile
    environment:
      - MONGO_URL=mongodb://localhost:27018/admin
      - REDIS_URL=redis://localhost:6378
    networks:
        - common
    depends_on:
      - mongo
      - redis

networks:
    common:

volumes:
    mongo-data:
    redis-data: